from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC 
from constant import globalConstant
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
import pytest
import openpyxl

class Test_Tobeto_Report:
    def setup_method(self):
        self.driver=webdriver.Chrome()
        self.driver.maximize_window()
        self.driver.get(globalConstant.URL)
        sleep(5)
    
    def teardown_method(self):
        self.driver.quit()

    def login(self, email, password):
        email_input = WebDriverWait(self.driver, 10).until(
            EC.visibility_of_element_located((By.XPATH, globalConstant.emailBox))
        )
        email_input.send_keys(email)

        password_input = WebDriverWait(self.driver, 10).until(
            EC.visibility_of_element_located((By.XPATH, globalConstant.passwordBox))
        )
        password_input.send_keys(password)

        login_button = WebDriverWait(self.driver, 10).until(
            EC.visibility_of_element_located((By.XPATH, globalConstant.loginButton))
        )
        login_button.click()

    def test_S14_C1(self):
        self.login(globalConstant.email, globalConstant.password)
        sleep(10)
        startButon=self.driver.find_element(By.XPATH,globalConstant.startButton12XPATH)
        actions = ActionChains(self.driver)
        actions.move_to_element(startButon).perform()
        sleep(3)
        startButon.click()
        sleep(3)
        experience=self.driver.find_element(By.XPATH,globalConstant.experienceXPATH)
        experience.click()
        sleep(3)
        corporationName=self.driver.find_element(By.XPATH,globalConstant.corporationNameXPATH)
        corporationName.send_keys("Tobeto")
        position=self.driver.find_element(By.XPATH,globalConstant.positionXPATH)
        position.send_keys("yazılım test")
        exSpecies=self.driver.find_element(By.XPATH,globalConstant.expSpeciesXPATH)
        exSpecies.click()
        sleep(2)
        # staj=self.driver.find_element(By.XPATH,globalconstant.stajXPATH)
        # staj.click()
        # sleep(2)
        # expList=self.driver.find_element(By.XPATH,globalconstant.experienceXPATH)
        # expList.click()
        # sleep(2)
        sector=self.driver.find_element(By.XPATH,globalConstant.sectorXPATH)
        sector.send_keys("yazılım")
        country=self.driver.find_element(By.XPATH,globalConstant.countryXPATH)
        country.send_keys("İstanbul")
        date=self.driver.find_element(By.XPATH,globalConstant.dateXPATH)
        date.send_keys("08.06.2024")
        sleep(3)
        # dateOff=self.driver.find_element(By.XPATH,globalconstant.dateOfXPATH)
        # dateOff.send_keys("10.06.2024")
        # sleep(5)
        checkBox=self.driver.find_element(By.XPATH,globalConstant.checkBoxXPATH)
        checkBox.click()
        desc=self.driver.find_element(By.XPATH,globalConstant.descXPATH)
        desc.send_keys("tobeto")
        sleep(3)
        save=self.driver.find_element(By.XPATH,globalConstant.saveXPATHH)
        save.click()
        sleep(2)
        expected1=self.driver.find_element(By.XPATH,globalConstant.expected1XPATH)
        assert expected1.text=="• Deneyim eklendi."

    def test_S14_C2(self):
        self.login(globalConstant.email, globalConstant.password)
        sleep(10)
        startButon=self.driver.find_element(By.XPATH,globalConstant.startButton12XPATH)
        actions = ActionChains(self.driver)
        actions.move_to_element(startButon).perform()
        sleep(7)
        startButon.click()
        sleep(5)
        experience=self.driver.find_element(By.XPATH,globalConstant.experienceXPATH)
        experience.click()
        sleep(5)
        corporationName=self.driver.find_element(By.XPATH,globalConstant.corporationNameXPATH)
        corporationName.send_keys("Tobeto")
        sleep(3)
        position=self.driver.find_element(By.XPATH,globalConstant.positionXPATH)
        position.send_keys("yazılım test")
        sleep(7)
        exSpecies=self.driver.find_element(By.XPATH,globalConstant.expSpeciesXPATH)
        exSpecies.click()
        sleep(3)
        # expList=self.driver.find_element(By.XPATH,globalconstant.experienceXPATH)
        # expList.click()
        sleep(2)
        sector=self.driver.find_element(By.XPATH,globalConstant.sectorXPATH)
        sector.send_keys("yazılım")
        country=self.driver.find_element(By.XPATH,globalConstant.countryXPATH)
        country.send_keys("İstanbul")
        date=self.driver.find_element(By.XPATH,globalConstant.dateXPATH)
        date.click()
        sleep(3)
        dateOff=self.driver.find_element(By.XPATH,globalConstant.dateOfXPATH)
        dateOff.click()
        sleep(3)
        # checkBox=self.driver.find_element(By.XPATH,globalconstant.checkBoxXPATH) iş bırakma tarihi seçildi.
        # checkBox.click()
        desc=self.driver.find_element(By.XPATH,globalConstant.descXPATH)
        desc.send_keys("tobetoqweeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeqweqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq")
        sleep(3)
        save=self.driver.find_element(By.XPATH,globalConstant.saveXPATHH)
        save.click()
        sleep(2)
        expected=self.driver.find_element(By.XPATH,globalConstant.expectedXPATH14)
        assert expected.text=="En fazla 300 karakter girebilirsiniz"

    def test_S14_C3(self):
        self.login(globalConstant.email, globalConstant.password)
        sleep(10)
        startButon=self.driver.find_element(By.XPATH,globalConstant.startButton12XPATH)
        actions = ActionChains(self.driver)
        actions.move_to_element(startButon).perform()
        sleep(7)
        startButon.click()
        sleep(5)
        experience=self.driver.find_element(By.XPATH,globalConstant.experienceXPATH)
        experience.click()
        sleep(5)
        corporationName=self.driver.find_element(By.XPATH,globalConstant.corporationNameXPATH)
        corporationName.send_keys("Tobe")
        position=self.driver.find_element(By.XPATH,globalConstant.positionXPATH)
        position.send_keys("yazı")
        exSpecies=self.driver.find_element(By.XPATH,globalConstant.expSpeciesXPATH)
        exSpecies.click()
        sleep(2)
        sector=self.driver.find_element(By.XPATH,globalConstant.sectorXPATH)
        sector.send_keys("yazı")
        sleep(3)
        country=self.driver.find_element(By.XPATH,globalConstant.countryXPATH)
        country.send_keys("İstanbul")
        sleep(3)
        date=self.driver.find_element(By.XPATH,globalConstant.dateXPATH)
        date.click()
        sleep(5)
        # dateOff=self.driver.find_element(By.XPATH,globalconstant.dateOfXPATH)  çalışmaya devam ediyorum kutucuğu seç.
        # dateOff.click()
        checkBox=self.driver.find_element(By.XPATH,globalConstant.checkBoxXPATH)
        checkBox.click()
        sleep(2)
        desc=self.driver.find_element(By.XPATH,globalConstant.descXPATH)
        desc.send_keys("tobeto")
        sleep(3)
        save=self.driver.find_element(By.XPATH,globalConstant.saveXPATHH)
        save.click()
        sleep(2)
        expectedC3=self.driver.find_element(By.XPATH,globalConstant.expectedXPATH14C3)
        assert expectedC3.text=="En az 5 karakter girmelisiniz"

    def test_S14_C4(self):
        self.login(globalConstant.email, globalConstant.password)
        sleep(10)
        startButon=self.driver.find_element(By.XPATH,globalConstant.startButton12XPATH)
        actions = ActionChains(self.driver)
        actions.move_to_element(startButon).perform()
        sleep(7)
        startButon.click()
        sleep(5)
        experience=self.driver.find_element(By.XPATH,globalConstant.experienceXPATH)
        experience.click()
        sleep(5)
        corporationName=self.driver.find_element(By.XPATH,globalConstant.corporationNameXPATH)
        corporationName.send_keys("Tobetooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo")
        sleep(3)
        position=self.driver.find_element(By.XPATH,globalConstant.positionXPATH)
        position.send_keys("yazılımmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm")
        sleep(3)
        exSpecies=self.driver.find_element(By.XPATH,globalConstant.expSpeciesXPATH)
        exSpecies.click()
        sleep(2)
        sector=self.driver.find_element(By.XPATH,globalConstant.sectorXPATH)
        sector.send_keys("yazılımmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm")
        sleep(3)
        country=self.driver.find_element(By.XPATH,globalConstant.countryXPATH)
        country.send_keys("İstanbul")
        sleep(3)
        date=self.driver.find_element(By.XPATH,globalConstant.dateXPATH)
        date.click()
        sleep(3)
        dateOff=self.driver.find_element(By.XPATH,globalConstant.dateOfXPATH)
        dateOff.click()
        sleep(3)
        # checkBox=self.driver.find_element(By.XPATH,globalconstant.checkBoxXPATH) çalışmaya decam ediyor kutucuğu
        # checkBox.click()
        desc=self.driver.find_element(By.XPATH,globalConstant.descXPATH)
        desc.send_keys("tobeto")
        sleep(3)
        save=self.driver.find_element(By.XPATH,globalConstant.saveXPATHH)
        save.click()
        sleep(2)
        exxpectedC4=self.driver.find_element(By.XPATH,globalConstant.expectedXPATHC4)
        assert exxpectedC4.text=="En fazla 50 karakter girebilirsiniz"

    def test_S14_C5(self):
        self.login(globalConstant.email, globalConstant.password)
        sleep(10)
        startButon=self.driver.find_element(By.XPATH,globalConstant.startButton12XPATH)
        actions = ActionChains(self.driver)
        actions.move_to_element(startButon).perform()
        sleep(7)
        startButon.click()
        sleep(5)
        experience=self.driver.find_element(By.XPATH,globalConstant.experienceXPATH)
        experience.click()
        sleep(5)
        corporationName=self.driver.find_element(By.XPATH,globalConstant.corporationNameXPATH)
        corporationName.send_keys("")
        position=self.driver.find_element(By.XPATH,globalConstant.positionXPATH)
        position.send_keys("")
        exSpecies=self.driver.find_element(By.XPATH,globalConstant.expSpeciesXPATH)
        exSpecies.click()
        sleep(2)
        sector=self.driver.find_element(By.XPATH,globalConstant.sectorXPATH)
        sector.send_keys("")
        country=self.driver.find_element(By.XPATH,globalConstant.countryXPATH)
        country.send_keys("İstanbul")
        date=self.driver.find_element(By.XPATH,globalConstant.dateXPATH)
        date.click()
        sleep(5)
        dateOff=self.driver.find_element(By.XPATH,globalConstant.dateOfXPATH)
        dateOff.click()
        sleep(5)
        desc=self.driver.find_element(By.XPATH,globalConstant.descXPATH)
        desc.send_keys("tobeto")
        save=self.driver.find_element(By.XPATH,globalConstant.saveXPATHH)
        save.click()
        sleep(2)
        exxpectedC5=self.driver.find_element(By.XPATH,globalConstant.expectedXPATHC5)
        assert exxpectedC5.text=="Doldurulması zorunlu alan*"