URL="https://tobeto.com/giris"
excelLogin="data/testLogin.xlsx"
emailBox="//input[@name='email']"
passwordBox="//input[@name='password']"
loginButton="//button[@type='submit']"
expectedResult="//p[contains(.,'Doldurulması zorunlu alan*')]"
excelMistake= "data/testMistakeLogin.xlsx"
mistakeError="//div[2]/div/div[2]"
singUp=".signup"
firstName="//input[@name='firstName']"
lastName="lastName"
eposta="email"
password="/html/body/div[1]/div/main/div[2]/div/div/form/div[4]/input"
passwordAgain="passwordAgain"
signUpButton="/html/body/div[1]/div/main/div[2]/div/div/button"
memberShipContract="/html/body/div[4]/div/div/div/div/div/label[2]/small/input"
contract="/html/body/div[4]/div/div/div/div/div/label[3]/small/input"
sendingEmail="/html/body/div[4]/div/div/div/div/div/label[4]/small/label[1]/input"
sendingPhone="/html/body/div[4]/div/div/div/div/div/label[4]/small/label[2]/input"
recaptchaButton="recaptcha-checkbox-checkmark"
againPhone="phoneNumber"
continueButton="//button[contains(.,'Devam Et')]"
successfulAlert="success-payment-text"
errorPhoneAlert="/html/body/div[5]/div/div/div/div/div/label[4]/small/p"
registeredEpostaError="//body/div[4]"
forgotPasswordButton="(//button[@type='button'])[3]"
passwordResetBox=".form-control"
sendButton=".btn:nth-child(3)"
passwordResetLink="https://tobeto.com/reset-password?code=2758bea9f493f252d5df7ac2f47f68adfc154e60b895345bbce63ccf1352a7f7989e4fbfcc2eeb401ed0fee78cc20a6b307afa4861bdcf6ff05b557de1124cdf"
newPassword="/html/body/div[1]/div/main/section/div/form/div/div/input[1]"
newPasswordAgain="/html/body/div[1]/div/main/section/div/form/div/div/input[2]"
newPasswordSend="/html/body/div[1]/div/main/section/div/form/div/div/button"
chatBox="/html/body/div/div/button/div/img"
symbolButton=".exw-minimize-button > path:nth-child(2)"
chatboxMessage="//html/body/div/div/div/div[2]/div[2]/div[2]/div[2]/input" 
sendNameButton="/html/body/div/div/div/div[2]/div[2]/div[2]/div[2]/svg"
tobetoAbout="/html/body/div/div/div/div[2]/div[3]/div/div/div/div[2]/div/div/div[1]"           
messageFinish=".exw-end-session-button"
yesButtonClick=".finishSessionCheckButtons > button:nth-child(1)"
emojiChoose="/html/body/div/div/div/div[2]/div[2]/div/div/form/div[2]/svg[1]"
emojiBox="/html/body/div/div/div/div[2]/div[2]/div/div/form/textarea"
surveyButton="/html/body/div/div/div/div[2]/div[2]/div/div/form/button"
emojiButton=".exw-add-emoji"
messageBox="//textarea[@name='message']"
emojiButtonClick="/html/body/div/div/div/div[3]/form/div/a/svg"
handButton="/html/body/div/div/div/div[3]/div[1]/div/emoji-picker//section/div[2]/div[2]/button"
addFile=".exw-add-file > svg"
chooseFile=".exw-drag-drop-select-button"
closeIkon=".exw-drag-drop-close-icon"
email="pair4test3a@gmail.com"
password="pair4test3a"
lessonsButton="#lessons-tab"
notificatonButton="#notification-tab"
surveyButton="#mySurvey-tab"
examName="//span[contains(.,'Herkes İçin Kodlama 5B Değerlendirme Sınavı')]"
report="//button[contains(.,'Raporu Görüntüle')]"
closeButton="//button[contains(.,'Kapat')]"
start1="//div[@id='__next']/div/main/div/section[4]/div/div/div/div/button"
start2="//div[@id='__next']/div/main/div/section[4]/div/div/div[2]/div/button"
start3="//div[@id='__next']/div/main/div/section[4]/div/div/div[3]/div/button"
showMoreButton="//div[@id='lessons-tab-pane']/div/div/div[2]"
goTo="//div[@id='all-lessons-tab-pane']/div/div[2]/div/div[2]/button"
education="//div[@id='all-lessons-tab-pane']/div/div[2]/div/div[2]/button"
addFavorite="/html/body/div/div[1]/div[1]/div/div[1]/div/div[2]/div/div[1]/div/div[2]/div/div[4]/div/span"
likeButton="/html/body/div/div[1]/div[1]/div/div[1]/div/div[2]/div/div[1]/div/div[2]/div/div[3]/div/div/span[1]/div"
aboutButton="//div[@id='rc-tabs-0-tab-about']/div/span"
contectButton="//span[contains(.,'İçerik')]"
detailButton="//div[@id='activity-unit-detail']/div/div[2]/div/div/div[2]/button/span"
goToLesson="//a[contains(text(),'EĞİTİME GİT')]"
xButton="//div[@id='root']/div/div[3]/div/div/div/a"
searchBox="//input[@id='search']"
listButton="/html/body/div/div/main/div[2]/div[1]/div/div[2]/div/div[1]/div[1]/div[2]"
searchList="/div[@id='__next']/div/main/div[2]/div/div/div[2]/div/div/div/div[2]"
alphabetListButton="/html/body/div/div/main/div[2]/div[1]/div/div[3]/div/div"
news="//button[@id='notification-tab']"
newsShowMore="/html/body/div[1]/div/main/div[1]/section[2]/div/div/div[3]/div/div[3]/div/div[4]"
startButton11XPATH="/html/body/div[1]/div/main/div[1]/section[4]/div/div/div[2]/div/button"
raporXPATH="//a[contains(text(),'Raporu Görüntüle')]"
okXPATH="//button[contains(.,'Bu yetkinlik nedir ve neden önemli?')]"
expectedResultSucceedXPATH="//div/div/div/div/div[2]"
expectedResultXPATH2="//p[contains(.,'Doldurulması zorunlu alan*')]"
expectedResultXPATH3="//div[2]/div/div[2]"
startButtonXPATH="//section[4]/div/div/div[2]/div/button"
startButton11XPATH="/html/body/div[1]/div/main/div[1]/section[4]/div/div/div[2]/div/button"
raporXPATH="//a[contains(text(),'Raporu Görüntüle')]"
okXPATH="//button[contains(.,'Bu yetkinlik nedir ve neden önemli?')]"                      
accountXPATH="//div[@id='__next']/div/nav/div/div/div/div[2]/button/div[2]/p"
profilXPATH="//a[contains(text(),'Profil Bilgileri')]"
startButton12XPATH="//div[@id='__next']/div/main/div/section[4]/div/div/div/div/button"
experienceXPATH="//span[contains(.,'Deneyimlerim')]"
educationsXPATH="//span[contains(.,'Eğitim Hayatım')]"
compentenciesXPATH="//span[contains(.,'Yetkinliklerim')]"
certificateXPATH="//span[contains(.,'Sertifikalarım')]"
memberXPATH="//span[contains(.,'Üye Topluluklar')]"
priceXPATH="//span[contains(.,'Projeler ve Ödüller')]"
personalAccountXPATH="//span[contains(.,'Medya Hesaplarım')]"
languageXPATH="//span[contains(.,'Yabancı Dillerim')]"
settingsXPATH="//span[contains(.,'Ayarlar')]"
start13XPATH="//div[@id='__next']/div/main/div/section[4]/div/div/div/div/button"
nameXPATH="//input[@name='name']"
lastnameXPATH="//input[@name='surname']"
phoneNumberXPATH="//input[@id='phoneNumber']"
birthdayXPATH="//input[@name='birthday']"
idXPATH="//input[@name='identifier']"
streetXPATH="//textarea[@name='address']"
textXPATH="//div[@id='__next']/div/main/section/div/div/div[2]/form/div/div[16]/textarea"
saveXPATH="/html/body/div[1]/div/main/section/div/div/div[2]/form/button"
expectedMessage_C1_XPATH="//div[@id='__next']/div/div/div/div[2]"   
profillXPATH="//div[@id='__next']/div/main/section/div/div/div[2]/form/div/div/div/div"
searchXPATH="//button[contains(.,'gözat')]"
addressXPATH="//textarea[@name='address']"
erMassageXPATH="/html/body/div[1]/div/main/section/div/div/div[2]/form/div/div[6]/span"
alertXPATH="/html/body/div/div/main/section/div/div/div[2]/form/div/div[15]/span"
alertXPATH2="/html/body/div/div/main/section/div/div/div[2]/form/div/div[16]/span"
corporationNameXPATH="//input[@name='corporationName']"
expSpeciesXPATH="//div[@id='__next']/div/main/section/div/div/div[2]/form/div/div[3]/div/div/div/div[2]"
expListXPATH="//div[@id='react-select-5-option-'Staj']" 
stajXPATH="//div[@class='select__option' and text()='staj']"  #chatgbt
positionXPATH="//input[@name='position']"
sectorXPATH="//input[@name='sector']"
countryXPATH="//select[@name='country']"
dateXPATH="//div[@id='__next']/div/main/section/div/div/div[2]/form/div/div[6]/div/div/input"
dateOfXPATH="/html/body/div[1]/div/main/section/div/div/div[2]/form/div/div[7]/div[1]/div/input"  
checkBoxXPATH="//input[@name='checkbox']"
descXPATH="//textarea[@name='description']"
saveXPATHH="//button[contains(.,'Kaydet')]"
expected1XPATH="//div[@id='__next']/div/div/div/div[2]"
expectedXPATH14="//span[contains(.,'En fazla 300 karakter girebilirsiniz')]"
expectedXPATH14C3="//span[contains(.,'En az 5 karakter girmelisiniz')]"
expectedXPATHC4="//span[contains(.,'En fazla 50 karakter girebilirsiniz')]"
expectedXPATHC5="//span[contains(.,'Doldurulması zorunlu alan*')]"
educationXPATH="educations"
profilXPATH="/html/body/div[1]/div/main/div[1]/section[4]/div/div/div[1]/div/button"
educationalbackgroundXPATH="/html/body/div[1]/div/main/section/div/div/div[2]/form"
saveXPATH="//button[contains(.,'Kaydet')]"
dropdownXPATH="select__dropdown-indicator"
yetkinliklerimXPATH="//span[contains(.,'Yetkinliklerim')]"
kaydetXPATH="//button[contains(.,'Kaydet')]"
messageXPATH="//div[@id='__next']/div/div/div/div[2]"
yetenekXPATH="/html/body/div/div/main/section/div/div/div[2]/div[1]/div/div/div/div[1]/div[2]"
message2XPATH="//div[@id='__next']/div/div/div/div[2]"
deleteXPATH="//div[@id='__next']/div/main/section/div/div/div[2]/div[2]/div/div/button"
yesXPATH="//button[contains(.,'Evet')]"
message3XPATH="//div[@id='__next']/div/div/div/div[2]"
sertifikalarımXPATH="/html/body/div[1]/div/main/section/div/div/div[1]/div/a[5]/span[2]"
sertifikaXPATH="//input[@name='CertificateName']"
tarihXPATH="/html/body/div[1]/div/main/section/div/div/div[2]/div[2]/form/div[1]/div[2]/div[1]/div/input"
gozatXPATH="//div[@id='__next']/div/main/section/div/div/div[2]/div[2]/form/div/div[3]/div/div/div/div[2]/div/div[2]/div/button"
delete2XPATH="//div[@id='__next']/div/main/section/div/div/div[2]/div[2]/div/div/div/table/tbody/tr/td[4]/span[2]"
yes2XPATH="//button[contains(.,'Evet')]"
message4XPATH="//div[@id='__next']/div/div/div/div[2]"
profilButton="//a[contains(text(),'Profilim')]"
edit="//div[@id='__next']/div/main/div/div/div/div/div[2]/div/div/span"
share="//button[@id='dropdown-basic']"
dropDown="//div[@id='__next']/div/main/div/div/div/div/div[2]/div/div/div/div/div/div/div"
copyLink="//div[@id='__next']/div/main/div/div/div/div/div[2]/div/div/div/div/div[2]/div/i"
certificate="/html/body/div[1]/div/main/div/div/div[2]/div/div[5]/div/div[2]/div/div"
socialMedia=".cv-linkedin"
seeIkon=".cv-see-icon"
reviews="//a[contains(text(),'Değerlendirmeler')]"
viewReport="//a[contains(text(),'Raporu Görüntüle')]"
report2="/html/body/div[1]/div/main/section[2]/div/div/div[4]/div/div[1]/button"
report3="//div[2]/div[2]/button"
rating=".nav-item:nth-child(3) > .c-gray-3"